import { defineStock } from './defineStock';

export const ETN = defineStock({
  ticker: 'ETN',
  name: 'Eaton Corporation plc',
  sector: 'Electrical Equipment / Electrification & Data Center Power',
  themeColor: '#0072ce',
  currentPrice: 404.07,
  updatedOn: '07/24',
  lastReportTag: 'Q1 2026',
  fairPriceRange: '$330 - $520',
  shares0: 389.2,
  rev25: 27448,
  fcfMargin25: 0.13,
  taxRate: 0.17,
  cash: 2000,
  debt: 12000,
  beta: 1.16,
  costDebt: 0.045,
  rsRating: 73,
  rsTrend: 'rising',
  aiImpact: 'TAILWIND',
  ratingOverride: 'HOLD',  // Floors ETN at HOLD: base DCF deeply negative on a high-multiple electrical name (RS 88), but OVERVALUED overstates a quality compounder. Matches RS-boosted model today.
  reasonsToBuy: [
    'Three simultaneous secular megatrends — AI data center power, grid modernization, and broad electrification — underpin multi-year demand visibility',
    'Data center orders growing at an extraordinary rate confirms Eaton\'s positioning at the critical power infrastructure layer',
    'Best-in-class EBITDA margins and strong buyback program demonstrate the operational quality of a mature industrial compounder',
    'Planned Mobility spin-off would concentrate the portfolio purely on high-growth electrification and data center power businesses',
    'Boyd Thermal acquisition deepens the liquid-cooling stack, expanding content per data center rack as AI density rises',
  ],

  risksToBuy: [
    'Valuation already reflects a full premium at roughly thirty-nine times trailing earnings with limited margin of safety',
    'FY26 segment-margin guidance was trimmed due to input costs, suggesting operating leverage is not yet as smooth as projected',
    'AI data center capex digestion could cause a sharp order deceleration after the current hyper-investment cycle peaks',
    'Industrial business lines face cyclical headwinds if global manufacturing activity slows materially from current levels',
    'Net debt of tens of billions limits financial flexibility if an acquisition or economic downturn requires rapid capital deployment',
  ],

  analystConsensus: { rating: 'Buy', targetLow: 321, targetMedian: 451, targetHigh: 534, numAnalysts: 19 },
  revGrowth: [
    [0.05, 0.04, 0.03, 0.03, 0.03],
    [0.09, 0.08, 0.08, 0.07, 0.06],
    [0.12, 0.11, 0.10, 0.10, 0.09],
  ],
  fcfMargin: [
    [0.13, 0.13, 0.14, 0.14, 0.14],
    [0.13, 0.14, 0.15, 0.15, 0.16],
    [0.14, 0.15, 0.16, 0.17, 0.18],
  ],
  exitMultiple: [14, 17, 20],
  desc: [
    'Data center capex digestion and an industrial down-cycle slow organic growth to mid-single digits. Margin expansion stalls as mix and pricing normalize. With the stock already at ~39× earnings, multiple compression toward 14× EBITDA dominates returns — the premium unwinds even as the business stays healthy.',
    'Electrification + AI data center power + reshoring sustain high-single-digit organic growth as the Electrical Americas backlog converts. FCF margin expands toward 16% on operating leverage; EPS compounds ~9%. A still-premium 17× EBITDA holds for a quality compounder — fair value lands near spot, so returns track earnings growth and the ~1% dividend.',
    'AI data center power demand proves structural and durable, grid/utility capex accelerates, and Eaton captures share with content gains per rack. Revenue compounds low-teens, FCF margin pushes toward 18%, and the market keeps paying 20× EBITDA for the cleanest electrification pure-play. Capital return and tuck-in M&A add optionality.',
  ],
  termGrowth: [0.02, 0.025, 0.03],
  bbRate: [0.005, 0.01, 0.015],
  ebitdaProxy: [0.22, 0.24, 0.26],
  burry: {
    sbc: 155,
    gaapNi: 4087,
    buyback: 1900,
    epsBasis: 'GAAP',
    fy: 'FY25',
    overstatementPct: 10,
    overstatementSource: 'estimated',
    note: 'Low SBC for a large-cap industrial — naive SBC/NI only ~4% on FY25 GAAP NI of $4,087M (SBC ~$155M est.; total disclosed only in 10-K notes). FY25 buybacks of $1.9B (10-K, $7.6B left on a $9.0B authorization) dwarf dilution. Pristine tier — owner profit closely tracks GAAP.',
  },
  debtSafety: {
    netDebt: 10000,
    ebitda: 6662,
    fy: 'FY25',
    note: 'Net debt/EBITDA ~1.5× (≤2.0 → GREEN) with interest coverage >20×. Traditional, well-managed corporate leverage; ample headroom.',
  },
});
