import { defineStock } from './defineStock';

export const ETN = defineStock({
  ticker: 'ETN',
  name: 'Eaton Corporation plc',
  sector: 'Electrical Equipment / Electrification & Data Center Power',
  themeColor: '#0072ce',
  currentPrice: 399.17,
  updatedOn: '06/07',
  lastReportTag: 'Q1 2026',
  fairPriceRange: '$330 - $520',
  shares0: 389.2,
  rev25: 27448,
  fcfMargin25: 0.13,
  taxRate: 0.17,
  cash: 2000,
  debt: 12000,
  beta: 1.16,
  costDebt: 0.045,
  rsRating: 88,
  rsTrend: 'rising',
  aiImpact: 'TAILWIND',
  ratingOverride: 'HOLD',
  strategicNarrative:
    "ETN is a best-in-class electrification and data-center-power compounder riding three secular megatrends at once: AI data center electrical buildout, grid modernization/reshoring, and the broad electrification of everything. FY25 revenue $27.4B (+10% organic momentum, TTM $28.5B as of Q1 2026) with EBITDA margins expanding past 23% on operating leverage (operational leverage ~0.96). Diluted EPS compounding ~9% (FY25 $10.45, +10% YoY) with a 41% payout ratio and steady buybacks (~0.7% yield). The Electrical Americas backlog and data-center order book give multi-year visibility, and the balance sheet is pristine (net debt/EBITDA ~1.5×, interest coverage >20×). The catch is valuation: at ~39× trailing earnings against a high-single-digit EPS CAGR, the market is already paying a full premium for the electrification story. The business quality is unimpeachable and momentum is strong (new highs, price ~21% above its 200-day), but the model fair value sits near or modestly below spot — most of the next several years of growth is priced in. Verdict: HOLD — own quality, but wait for a pullback or growth re-acceleration to add at these levels.",
  analystConsensus: { rating: 'Buy', targetLow: 321, targetMedian: 451, targetHigh: 534, numAnalysts: 19 },
  revGrowth: [
    [0.05, 0.04, 0.03, 0.03, 0.03],
    [0.09, 0.08, 0.08, 0.07, 0.06],
    [0.12, 0.11, 0.10, 0.10, 0.09],
  ],
  fcfMargin: [
    [0.13, 0.13, 0.14, 0.14, 0.14],
    [0.13, 0.14, 0.15, 0.15, 0.16],
    [0.14, 0.15, 0.16, 0.17, 0.18],
  ],
  exitMultiple: [14, 17, 20],
  desc: [
    'Data center capex digestion and an industrial down-cycle slow organic growth to mid-single digits. Margin expansion stalls as mix and pricing normalize. With the stock already at ~39× earnings, multiple compression toward 14× EBITDA dominates returns — the premium unwinds even as the business stays healthy.',
    'Electrification + AI data center power + reshoring sustain high-single-digit organic growth as the Electrical Americas backlog converts. FCF margin expands toward 16% on operating leverage; EPS compounds ~9%. A still-premium 17× EBITDA holds for a quality compounder — fair value lands near spot, so returns track earnings growth and the ~1% dividend.',
    'AI data center power demand proves structural and durable, grid/utility capex accelerates, and Eaton captures share with content gains per rack. Revenue compounds low-teens, FCF margin pushes toward 18%, and the market keeps paying 20× EBITDA for the cleanest electrification pure-play. Capital return and tuck-in M&A add optionality.',
  ],
  termGrowth: [0.02, 0.025, 0.03],
  bbRate: [0.005, 0.01, 0.015],
  ebitdaProxy: [0.22, 0.24, 0.26],
  burry: {
    sbc: 170,
    gaapNi: 4087,
    buyback: 1000,
    epsBasis: 'GAAP',
    fy: 'FY25',
    overstatementPct: 10,
    overstatementSource: 'estimated',
    note: 'Low SBC for a large-cap industrial — naive SBC/NI only ~4% on FY25 GAAP NI of $4,087M. Even with the MTM amplifier from a ~3× stock run, buybacks (~$1B/yr) more than cover dilution. Pristine tier — owner profit closely tracks GAAP.',
  },
  debtSafety: {
    netDebt: 10000,
    ebitda: 6662,
    fy: 'FY25',
    note: 'Net debt/EBITDA ~1.5× (≤2.0 → GREEN) with interest coverage >20×. Traditional, well-managed corporate leverage; ample headroom.',
  },
});
