import { defineStock } from './defineStock';

export const INCY = defineStock({
  ticker: 'INCY',
  name: 'Incyte Corporation',
  sector: 'Biopharmaceuticals / Oncology & Dermatology',
  themeColor: '#00a3a1',
  currentPrice: 116.71,
  updatedOn: '07/10',
  lastReportTag: 'Q1 2026',
  fairPriceRange: '$85 - $135',
  shares0: 200,
  rev25: 5140,
  fcfMargin25: 0.20,
  taxRate: 0.19,
  cash: 3600,
  debt: 0,
  beta: 0.65,
  costDebt: 0.04,
  rsRating: 65,
  rsTrend: 'rising',
  aiImpact: 'NEUTRAL',
  ratingOverride: 'HOLD',  // Model now screens BUY (eased below the STRONG BUY threshold as spot recovered) but the Jakafi loss-of-exclusivity overhang caps the multiple; consensus Buy. HOLD.
  reasonsToBuy: [
    'Cheap valuation relative to earnings power reflects overstated fear about the Jakafi patent cliff',
    'Fortress balance sheet with substantial net cash and zero long-term debt funds the R&D transition with no dilution risk',
    'Opzelura in vitiligo and atopic dermatitis is a multi-year growth franchise still in early commercial penetration',
    'Niktimvo and povorcitinib represent credible pipeline diversification beyond the Jakafi-dependent revenue base',
    'Standing M&A target optionality — profitable, debt-free, and undervalued relative to large-cap pharma acquirers',
  ],

  risksToBuy: [
    'Jakafi loss of exclusivity creates a revenue cliff that the pipeline must overcome with unproven commercial execution',
    'Pipeline readouts are binary events where trial failures could materially reset revenue expectations post-2028',
    'Low relative strength rating signals weak institutional sponsorship and limited near-term price momentum',
    'Revenue is heavily concentrated in one aging asset, making the business unusually vulnerable until diversification proves out',
    'Modest analyst upside consensus implies the current valuation already reflects the optionality premium fairly',
  ],

  analystConsensus: { rating: 'Buy', targetLow: 85, targetMedian: 108, targetHigh: 124, numAnalysts: 13 },
  revGrowth: [
    [0.05, 0.00, -0.08, -0.05, 0.00],
    [0.10, 0.06, 0.00, 0.03, 0.05],
    [0.14, 0.12, 0.06, 0.08, 0.10],
  ],
  fcfMargin: [
    [0.18, 0.16, 0.13, 0.13, 0.14],
    [0.20, 0.20, 0.20, 0.21, 0.22],
    [0.22, 0.23, 0.24, 0.25, 0.26],
  ],
  exitMultiple: [8, 11, 14],
  desc: [
    'Jakafi loss of exclusivity around 2028 bites hard as generic ruxolitinib floods the myelofibrosis/polycythemia vera market, and the pipeline fails to fill the gap. Revenue declines mid-single digits, FCF margin compresses toward 13%, and the market re-rates to a value-trap 8× EBITDA on a shrinking-franchise narrative.',
    'The diversified pipeline cushions the Jakafi cliff: Opzelura keeps compounding in dermatology, Niktimvo and Monjuvi add scale, and povorcitinib/oncology readouts offset the generic erosion. Revenue holds roughly flat through the LOE trough then resumes mid-single-digit growth. FCF margin stabilizes near 20%; an 11× EBITDA reflects a steady, cash-generative specialty pharma — fair value lands near spot.',
    'Pipeline execution outruns the cliff — Opzelura reaches blockbuster scale, Niktimvo/povorcitinib launches exceed expectations, and the oncology/MRGPRX2 programs deliver. Revenue compounds high-single to low-double digits, FCF margin pushes past 25%, and the debt-free balance sheet plus standing M&A optionality drive a re-rate to 14× EBITDA.',
  ],
  termGrowth: [0.01, 0.02, 0.025],
  bbRate: [0.005, 0.01, 0.02],
  ebitdaProxy: [0.24, 0.28, 0.32],
  burry: {
    sbc: 249,
    gaapNi: 1300,
    buyback: 0,
    epsBasis: 'GAAP',
    fy: 'FY25',
    overstatementPct: 25,
    overstatementSource: 'estimated',
    note: 'FY25 SBC $249.3M (10-K) on GAAP NI ~$1.3B = naive SBC/NI ~19%, typical for biopharma. Range-bound/down stock keeps the MTM amplifier low (~1.3×) → ~25%. No buyback offset in FY25 — the $2.0B/$1.67B Dutch-auction tender was a 2024 event; in 2025 cash built from $2.2B to $3.6B with no material repurchases. OK tier — owner profit ~75% of GAAP.',
  },
  debtSafety: {
    netDebt: -3600,
    ebitda: 1440,
    fy: 'FY25',
    note: 'Net cash fortress — $3.6B cash/securities and zero long-term debt. No leverage risk; balance sheet funds the Jakafi-cliff transition.',
  },
});
