import { defineStock } from './defineStock';

export const ORCL = defineStock({
  ticker: 'ORCL',
  name: 'Oracle Corporation',
  sector: 'Cloud / Enterprise Software',
  themeColor: '#c74634',
  updatedOn: '07/09',
  lastReportTag: 'Q3 FY26',
  currentPrice: 144.22,
  fairPriceRange: '$140 - $380',
  shares0: 2870,
  rev25: 57400,
  fcfMargin25: 0.005,
  taxRate: 0.19,
  cash: 17000,
  debt: 88000,
  beta: 1.10,
  costDebt: 0.045,
  modelType: 'EPS_PE',
  baseEps: 6.03,
  rsRating: 47,
  rsTrend: 'rising',
  aiImpact: 'TAILWIND',
  reasonsToBuy: [
    'Oracle Database lock-in is among the deepest moats in enterprise software — migration cost is prohibitive',
    'OCI bare-metal architecture offers a structural cost advantage for large-scale AI training workloads',
    'Multicloud database strategy embeds Oracle directly inside AWS, Azure, and Google ecosystems',
    'RPO of record magnitude provides multi-year revenue visibility that few infrastructure players can match',
    'Q3 FY26 marked the first genuine dual-acceleration quarter in over a decade — the inflection appears real',
  ],

  risksToBuy: [
    'Heavy AI capex has temporarily destroyed free cash flow and may not convert if OCI stays fourth in cloud',
    'Gross margin compression from infrastructure buildout could persist well beyond the near term',
    'Balance sheet carries substantial debt accumulated through years of buybacks and now capex spending',
    'RS at deeply oversold levels reflects institutional skepticism about OCI\'s ability to close the gap on AWS and Azure',
    'SBC overstatement is among the highest in our coverage — real owner earnings are a fraction of reported GAAP',
  ],

  epsCagr: [9, 15, 21],
  exitPE: [15, 20, 24],
  prob: [20, 50, 30],

  analystConsensus: { rating: 'Buy', targetLow: 185, targetMedian: 276, targetHigh: 345, numAnalysts: 33 },
  revGrowth: [
    [0.12, 0.10, 0.08, 0.07, 0.06],
    [0.17, 0.32, 0.22, 0.20, 0.18],
    [0.25, 0.38, 0.28, 0.22, 0.18],
  ],
  fcfMargin: [
    [0.005, 0.02, 0.05, 0.08, 0.10],
    [0.005, 0.03, 0.08, 0.12, 0.15],
    [0.01, 0.05, 0.10, 0.15, 0.20],
  ],
  exitMultiple: [12, 18, 22],
  desc: [
    'AI infra cycle cools — OCI stays 4th behind AWS/Azure/GCP. Heavy capex ($21B→$71B) converts poorly to revenue. FCF stays depressed through 2028+. Gross margin compresses to 55% without revenue scale to compensate. EPS growth ~9% CAGR mostly from buybacks. Market reprices to 15× historical range. Price target ~$139, CAGR ~-4%. Key trigger: AI capex rationalization or OCI contract losses.',
    'Solid execution on Q3 FY26 momentum — OCI captures meaningful AI workload share, multicloud DB adoption sustains. Revenue hits $90B FY27 per raised guidance. RPO converts to revenue on schedule. Capex peaks FY28 then moderates, FCF inflects positive FY28-29. EPS compounds ~15% on operating leverage + scale. Partner-funded capacity model works. P/E stabilizes at 20× as market reclassifies Oracle from legacy to AI-enabled enterprise platform. Price target ~$242, CAGR ~8%.',
    'AI infrastructure boom extends multi-year. Oracle wins 3-4 major AI lab training contracts ($1-10B each). OCI bare-metal architecture becomes standard for large-scale training. Multicloud DB revenue sustains 100%+ growth. Revenue approaches $226B by 2030E. Sovereign/regulated cloud wins add durability. EPS ~21% CAGR on massive operating leverage. Market awards 24× as Oracle enters top-3 cloud. Price target ~$375, CAGR ~17%.',
  ],
  thesis: [
    'AI capex cycle peaks FY27 without sufficient OCI revenue conversion. Hyperscalers consolidate AI workloads on own platforms. Oracle cloud remains niche — enterprise DB customers migrate slowly but AI-native startups choose AWS/Azure. Massive debt ($88B) limits flexibility during downturn. Gross margins compress to 55% without scale. RPO proves partly "air" — contracted but low utilization. Stock re-rates to historical 12-15× legacy software multiple.',
    'Q3 FY26 proves the inflection is real — first 20%+ organic growth quarter in 15 years followed by sustained execution. Multicloud DB strategy (Azure/AWS/Google) widens moat beyond legacy lock-in into data gravity. OCI 84% cloud infra growth sustains 40%+ through FY28. Partner-funded capacity model ($29B signed) reduces balance sheet risk. AI halo effect drives cross-sell into applications, sovereign cloud. Capex peaks FY28, FCF recovers sharply. Stock re-rates from legacy discount to cloud premium over 2-3 years.',
    'Full AI infrastructure super-cycle over 10+ years. Oracle unique bare-metal GPU architecture wins training workloads that AWS/Azure price out. Gigantic cluster capability (10+ GW secured) becomes structural advantage. Multicloud database evolves into AI Data Platform — system of record + agent layer. Enterprise customers consolidate full stack on Oracle. RPO grows to $200B+. FCF margins expand to 20% as capex normalizes. Oracle becomes the "value hyperscaler" — the Costco of cloud.',
  ],

  bbRate: [0.010, 0.015, 0.020],
  ebitdaProxy: [0.35, 0.42, 0.45],
  termGrowth: [0.015, 0.025, 0.035],

  burry: {
    sbc: 4674,
    gaapNi: 12400,
    buyback: 150,
    epsBasis: 'NON_GAAP',
    fy: 'FY25',
    overstatementPct: 65,
    overstatementSource: 'estimated',
    note: 'Estimated ~65% overstatement — naive SBC/NI already at 38% (well above 30% Critical), and AI capex has consumed buyback capacity to ~$150M (vs $4.7B SBC), so dilution is essentially unoffset. Under full-SBC adjustment with MTM at $196 share price (~2.5× 3yr), real owner earnings ~35% of GAAP. Switching baseEps from non-GAAP $6.03 to GAAP $4.34 alone would already trim valuation materially.',
  },
  debtSafety: {
    netDebt: 71000,
    ebitda: 22000,
    capexToOcf: 0.37,
    interestCoverage: 3.7,
    altmanZ: 2.4,
    fy: 'FY25',
    note: 'AI data center buildout has temporarily crushed FCF (CapEx surging from $7B → $21B+). Interest coverage weak at 3.7× on $88B debt. High leverage on a still-transitioning cloud business is the core risk — if OCI revenue ramp disappoints, this balance sheet is a trap.',
  },
});
